### ISSUE TITLE
Open with `file_browser`

### ISSUE THREAD

**Issue by farzadmf** [tsakirist/telescope-lazy.nvim#2]
First of all, thank you for this; very useful!

Suggestion: [telescope-packer](https://github.com/nvim-telescope/telescope-packer.nvim) seems to also have an option to "open with `file_browser`", which I think can be useful.

**Comment by tsakirist** [comment]
Thanks for the suggestion.

I'll look into adding that functionality too.

**Comment by farzadmf** [comment]
Hey @tsakirist , thank you for getting into this so quickly

However, it doesn't seem to work for me, when I press `Alt+b` on a plugin, I think the file browser window appears for less than a second and disappears. I tried changing the mapping to something like `<C-r>b`, but the same thing happens.

The funny thing is that, after that happens, `file_browser` seems to break as well, and when I do `:Telescope file_browser`, nothing happens

**Comment by tsakirist** [comment]
Hello, can't reproduce it locally neither on my end nor on my colleagues.

I've tried a minimal config with only telescope related plugins and this extension and it works.

Make sure to double check your file browser configuration to see if something interferes. Since the only thing this extension does is to just call the file browser API.

Also provide a minimal reproducible example to help me debug too, since it's not reproducible on my end.
