### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by albertfgu** [tsakirist/telescope-lazy.nvim#4]
I'm using LazyVim and installed the plugin using the described method. Running `:Telescope lazy` gives the message "ERROR [telescope.run_command]: Unknown command"

Reproduction:
1. Follow https://www.lazyvim.org/installation for fresh installation of LazyVim
2. Add telescope-lazy
3. Attempt to use telescope-lazy

**Comment by tsakirist** [comment]
This is probably because you have not registered the extension in the telescope module during setup.

For example using __LazyVimStarter__ as the starter template, do the following:

1. Create a new file `telescope_lazy.lua` in the `plugins` directory
2. Put the following contents inside:
```lua
return {
  "tsakirist/telescope-lazy.nvim",
  dependencies = "nvim-telescope/telescope.nvim",
  config = function()
    require("telescope").load_extension("lazy")
    -- Can possible add other configuration as described in the README.md
  end,
}
```
3. Use `:Telescope lazy` it should work now

Does that fix your issue?

**Comment by albertfgu** [comment]
You were right, I didn't load the extension in `config` and was trying to load it elsewhere. Thank you so much!
